In [73]:
import numpy as np 
import matplotlib.pyplot as plt 


In [74]:
#import data
X = np.array([
    [2, 3],
    [1, 1],
    [2, 1],
    [3, 1.5],
    [-1, -1],
    [-2, -1.5],
    [-1.5, -2],
    [-2.5, -2]
])

y = np.array([1, 1, 1, 1, -1, -1, -1, -1])

In [75]:
print(X.shape)
y.shape

(8, 2)


(8,)

In [76]:
X_ones = np.ones((X.shape[0],1))

In [77]:
X_ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [78]:
X_concat = np.concatenate((X_ones,X),axis = 1)

In [79]:
X_concat

array([[ 1. ,  2. ,  3. ],
       [ 1. ,  1. ,  1. ],
       [ 1. ,  2. ,  1. ],
       [ 1. ,  3. ,  1.5],
       [ 1. , -1. , -1. ],
       [ 1. , -2. , -1.5],
       [ 1. , -1.5, -2. ],
       [ 1. , -2.5, -2. ]])

In [80]:
X_concat.shape

(8, 3)

In [81]:
#Initialize params
np.random.seed(1)
w = np.random.rand(X_concat.shape[1])

In [82]:
w.T

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [83]:
w.shape

(3,)

In [84]:
def check_misclassified(X,y,w):
    predict = np.sign(np.dot(X,w))
    return np.where(predict != y)[0]                # trả về 1 tuple các index mà tại đó bị misclassified




In [ ]:
#Run algorithm
epoch = 0 
while True:
    misclass_idx = check_misclassified(X_concat,y,w)
    if len(misclass_idx) == 0 : 
        break
    idx = np.random.choice(misclass_idx)
    
    #update 
    w = w + y[idx] * X_concat[idx]
    epoch = epoch + 1

    X_pos = X[y==1]
    print(X_pos)
    X_neg = X[y==-1]



    
    

    plt.legend("Numer of epochs" + str)(epoch)


                    

In [86]:
w 

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])